export const mockProducts = [
  {
    id: 1,
    name: "Kẹp tóc cao cấp",
    price: "150.000đ",
    image: "/images/product1.jpg",
    rating: 4,
    reviews: 12,
    isNew: true,
  },
  {
    id: 2,
    name: "Dây buộc tóc lụa",
    price: "89.000đ",
    image: "/images/product2.jpg",
    rating: 5,
    reviews: 8,
    isNew: false,
  },
  {
    id: 3,
    name: "Băng đô thời trang",
    price: "120.000đ",
    image: "/images/product3.jpg",
    rating: 4,
    reviews: 10,
    isNew: false,
  },
  {
    id: 4,
    name: "Cài tóc ngọc trai",
    price: "180.000đ",
    image: "/images/product4.jpg",
    rating: 5,
    reviews: 25,
    isNew: true,
  },
  {
    id: 5,
    name: "Kẹp càng cua bản to",
    price: "99.000đ",
    image: "/images/product5.jpg",
    rating: 3,
    reviews: 7,
    isNew: false,
  },
  {
    id: 6,
    name: "Scrunchie voan cao cấp",
    price: "75.000đ",
    image: "/images/product6.jpg",
    rating: 5,
    reviews: 18,
    isNew: true,
  },
  {
    id: 7,
    name: "Kẹp tóc Hàn Quốc",
    price: "135.000đ",
    image: "/images/product7.jpg",
    rating: 4,
    reviews: 12,
    isNew: false,
  },
  {
    id: 8,
    name: "Bộ kẹp tóc mini 10 món",
    price: "59.000đ",
    image: "/images/product8.jpg",
    rating: 4,
    reviews: 20,
    isNew: true,
  },
  {
    id: 9,
    name: "Kẹp tóc đính đá",
    price: "200.000đ",
    image: "/images/product9.jpg",
    rating: 5,
    reviews: 15,
    isNew: true,
  },
  {
    id: 10,
    name: "Dây cột tóc vintage",
    price: "89.000đ",
    image: "/images/product10.jpg",
    rating: 3,
    reviews: 5,
    isNew: false,
  },
  {
    id: 11,
    name: "Kẹp tóc gọng kim loại",
    price: "110.000đ",
    image: "/images/product11.jpg",
    rating: 4,
    reviews: 9,
    isNew: false,
  },
  {
    id: 12,
    name: "Dây buộc tóc hoa nhí",
    price: "69.000đ",
    image: "/images/product12.jpg",
    rating: 4,
    reviews: 6,
    isNew: true,
  },
  {
    id: 13,
    name: "Cài tóc băng đô thể thao",
    price: "95.000đ",
    image: "/images/product13.jpg",
    rating: 4,
    reviews: 11,
    isNew: true,
  },
  {
    id: 14,
    name: "Kẹp tóc hình nơ",
    price: "85.000đ",
    image: "/images/product14.jpg",
    rating: 5,
    reviews: 13,
    isNew: false,
  },
  {
    id: 15,
    name: "Set dây buộc tóc 5 cái",
    price: "45.000đ",
    image: "/images/product15.jpg",
    rating: 3,
    reviews: 4,
    isNew: false,
  },
  {
    id: 16,
    name: "Kẹp tóc acrylic thời trang",
    price: "155.000đ",
    image: "/images/product16.jpg",
    rating: 5,
    reviews: 17,
    isNew: true,
  },
  {
    id: 17,
    name: "Kẹp tóc hình lá",
    price: "130.000đ",
    image: "/images/product17.jpg",
    rating: 4,
    reviews: 10,
    isNew: false,
  },
  {
    id: 18,
    name: "Băng đô thun cotton",
    price: "50.000đ",
    image: "/images/product18.jpg",
    rating: 4,
    reviews: 7,
    isNew: false,
  },
  {
    id: 19,
    name: "Cài tóc ren đi tiệc",
    price: "210.000đ",
    image: "/images/product19.jpg",
    rating: 5,
    reviews: 22,
    isNew: true,
  },
  {
    id: 20,
    name: "Dây buộc tóc handmade",
    price: "80.000đ",
    image: "/images/product20.jpg",
    rating: 4,
    reviews: 6,
    isNew: false,
  },
  {
    id: 21,
    name: "Kẹp tóc mạ vàng sang trọng",
    price: "250.000đ",
    image: "/images/product21.jpg",
    rating: 5,
    reviews: 30,
    isNew: true,
  },
  {
    id: 22,
    name: "Dây buộc tóc cotton đơn giản",
    price: "55.000đ",
    image: "/images/product22.jpg",
    rating: 3,
    reviews: 3,
    isNew: false,
  },
  {
    id: 30,
    name: "Lược chải tóc gập du lịch",
    price: "45.000đ",
    image: "/images/product30.jpg",
    rating: 4,
    reviews: 6,
    isNew: true,
  },
  {
    id: 31,
    name: "Máy uốn tóc mini không dây",
    price: "320.000đ",
    image: "/images/product31.jpg",
    rating: 5,
    reviews: 25,
    isNew: true,
  },
  {
    id: 32,
    name: "Băng đô rửa mặt dễ thương",
    price: "55.000đ",
    image: "/images/product32.jpg",
    rating: 4,
    reviews: 12,
    isNew: false,
  },
  {
    id: 33,
    name: "Dây buộc tóc lụa hoa văn Nhật",
    price: "99.000đ",
    image: "/images/product33.jpg",
    rating: 5,
    reviews: 10,
    isNew: true,
  },
  {
    id: 34,
    name: "Kẹp càng cua pha lê",
    price: "165.000đ",
    image: "/images/product34.jpg",
    rating: 4,
    reviews: 9,
    isNew: false,
  },
  {
    id: 35,
    name: "Dây buộc tóc 3 tầng kiểu Pháp",
    price: "110.000đ",
    image: "/images/product35.jpg",
    rating: 5,
    reviews: 13,
    isNew: true,
  },
  {
    id: 36,
    name: "Kẹp tóc mái mini hình trái cây",
    price: "45.000đ",
    image: "/images/product36.jpg",
    rating: 4,
    reviews: 6,
    isNew: true,
  },
  {
    id: 37,
    name: "Băng đô thể thao cotton",
    price: "70.000đ",
    image: "/images/product37.jpg",
    rating: 3,
    reviews: 5,
    isNew: false,
  },
  {
    id: 38,
    name: "Set lược và gương gập tiện lợi",
    price: "89.000đ",
    image: "/images/product38.jpg",
    rating: 4,
    reviews: 8,
    isNew: false,
  },
  {
    id: 39,
    name: "Lược tròn sấy tóc chuyên dụng",
    price: "150.000đ",
    image: "/images/product39.jpg",
    rating: 5,
    reviews: 20,
    isNew: true,
  },
  {
    id: 40,
    name: "Cài tóc băng đô kim tuyến",
    price: "95.000đ",
    image: "/images/product40.jpg",
    rating: 4,
    reviews: 10,
    isNew: false,
  },
  {
    id: 41,
    name: "Bộ dây buộc tóc pastel 10 cái",
    price: "69.000đ",
    image: "/images/product41.jpg",
    rating: 4,
    reviews: 7,
    isNew: true,
  },
  {
    id: 42,
    name: "Máy duỗi tóc mini",
    price: "290.000đ",
    image: "/images/product42.jpg",
    rating: 5,
    reviews: 19,
    isNew: true,
  },
  {
    id: 43,
    name: "Kẹp tóc nhún ren thời trang",
    price: "115.000đ",
    image: "/images/product43.jpg",
    rating: 4,
    reviews: 9,
    isNew: false,
  },
  {
    id: 44,
    name: "Dây buộc tóc hình thú dễ thương",
    price: "59.000đ",
    image: "/images/product44.jpg",
    rating: 5,
    reviews: 11,
    isNew: true,
  },
  {
    id: 45,
    name: "Lược massage da đầu",
    price: "80.000đ",
    image: "/images/product45.jpg",
    rating: 4,
    reviews: 14,
    isNew: false,
  },
  {
    id: 46,
    name: "Kẹp tóc dài bản mảnh Hàn Quốc",
    price: "125.000đ",
    image: "/images/product46.jpg",
    rating: 5,
    reviews: 15,
    isNew: true,
  },
  {
    id: 47,
    name: "Bộ kẹp tóc lấp lánh dự tiệc",
    price: "190.000đ",
    image: "/images/product47.jpg",
    rating: 5,
    reviews: 22,
    isNew: true,
  },
  {
    id: 48,
    name: "Băng đô nơ vải nhung",
    price: "105.000đ",
    image: "/images/product48.jpg",
    rating: 4,
    reviews: 10,
    isNew: false,
  },
  {
    id: 49,
    name: "Set kẹp tóc hoạt hình 5 món",
    price: "75.000đ",
    image: "/images/product49.jpg",
    rating: 4,
    reviews: 7,
    isNew: true,
  },
  {
    id: 50,
    name: "Sáp vuốt tóc Clay Strong Hold",
    price: "210.000đ",
    image: "/images/product50.jpg",
    rating: 5,
    reviews: 32,
    isNew: true,
  },
  {
    id: 51,
    name: "Máy sấy tóc mini gấp gọn",
    price: "290.000đ",
    image: "/images/product51.jpg",
    rating: 4,
    reviews: 14,
    isNew: false,
  },
  {
    id: 52,
    name: "Băng đô thể thao nam thoáng khí",
    price: "85.000đ",
    image: "/images/product52.jpg",
    rating: 4,
    reviews: 10,
    isNew: true,
  },
  {
    id: 53,
    name: "Lược tạo kiểu răng thưa nam",
    price: "60.000đ",
    image: "/images/product53.jpg",
    rating: 3,
    reviews: 6,
    isNew: false,
  },
  {
    id: 54,
    name: "Sáp tạo kiểu tóc bóng mượt",
    price: "230.000đ",
    image: "/images/product54.jpg",
    rating: 5,
    reviews: 20,
    isNew: true,
  },
  {
    id: 55,
    name: "Set 3 băng đô thể thao unisex",
    price: "120.000đ",
    image: "/images/product55.jpg",
    rating: 4,
    reviews: 11,
    isNew: false,
  },
  {
    id: 56,
    name: "Máy duỗi tóc mini bản nhỏ",
    price: "310.000đ",
    image: "/images/product56.jpg",
    rating: 5,
    reviews: 18,
    isNew: true,
  },
  {
    id: 57,
    name: "Kẹp tóc nam màu đen đơn giản",
    price: "75.000đ",
    image: "/images/product57.jpg",
    rating: 4,
    reviews: 7,
    isNew: false,
  },
  {
    id: 58,
    name: "Gel vuốt tóc tạo kiểu Wet Look",
    price: "170.000đ",
    image: "/images/product58.jpg",
    rating: 4,
    reviews: 9,
    isNew: true,
  },
  {
    id: 59,
    name: "Lược tròn gỗ tạo phồng tóc nam",
    price: "145.000đ",
    image: "/images/product59.jpg",
    rating: 5,
    reviews: 12,
    isNew: false,
  },
  {
    id: 60,
    name: "Lược điện tạo kiểu tóc đa năng",
    price: "350.000đ",
    image: "/images/product60.jpg",
    rating: 5,
    reviews: 22,
    isNew: true,
  },
  {
    id: 61,
    name: "Set cột tóc da PU sang trọng",
    price: "99.000đ",
    image: "/images/product61.jpg",
    rating: 4,
    reviews: 8,
    isNew: true,
  },
  {
    id: 62,
    name: "Cài tóc thể thao nam nữ",
    price: "75.000đ",
    image: "/images/product62.jpg",
    rating: 4,
    reviews: 6,
    isNew: false,
  },
  {
    id: 63,
    name: "Kẹp tóc gọng sắt phong cách unisex",
    price: "95.000đ",
    image: "/images/product63.jpg",
    rating: 5,
    reviews: 10,
    isNew: true,
  },
  {
    id: 64,
    name: "Xịt giữ nếp tóc nam Max Hold",
    price: "180.000đ",
    image: "/images/product64.jpg",
    rating: 4,
    reviews: 13,
    isNew: true,
  },
  {
    id: 65,
    name: "Gôm xịt tóc siêu cứng",
    price: "210.000đ",
    image: "/images/product65.jpg",
    rating: 5,
    reviews: 16,
    isNew: false,
  },
  {
    id: 66,
    name: "Bộ lược và kéo cắt tóc tại nhà",
    price: "250.000đ",
    image: "/images/product66.jpg",
    rating: 4,
    reviews: 15,
    isNew: true,
  },
  {
    id: 67,
    name: "Lược đôi gập gọn nam nữ",
    price: "55.000đ",
    image: "/images/product67.jpg",
    rating: 4,
    reviews: 5,
    isNew: true,
  },
  {
    id: 68,
    name: "Kẹp tóc nam dáng cổ điển",
    price: "85.000đ",
    image: "/images/product68.jpg",
    rating: 4,
    reviews: 9,
    isNew: false,
  },
  {
    id: 69,
    name: "Combo tạo kiểu tóc nam chuyên nghiệp",
    price: "420.000đ",
    image: "/images/product69.jpg",
    rating: 5,
    reviews: 30,
    isNew: true,
  },
];

export const mockCategoryProductAccessNews = {
  _id: {
    $oid: "67f484f615263aa0fa7325dc",
  },
  name: "Tin tức & Mẹo làm đẹp",
  slug: "tin-tuc-and-meo-lam-dep",
  description:
    "Cập nhật những xu hướng làm đẹp mới nhất và các mẹo chăm sóc tóc",
  parentCategories: [],
  isActive: true,
  type: "blog",
  createdAt: {
    $date: "2025-04-08T02:07:50.791Z",
  },
  updatedAt: {
    $date: "2025-04-08T02:07:50.791Z",
  },
  __v: 0,
};
export const mockCategoryShareType = {
  _id: {
    $oid: "67f484d815263aa0fa7325cf",
  },
  name: "Gợi ý phong cách",
  slug: "goi-y-phong-cach",
  parentCategories: [],
  isActive: true,
  type: "blog",
  createdAt: {
    $date: "2025-04-08T02:07:20.381Z",
  },
  updatedAt: {
    $date: "2025-04-08T02:08:25.075Z",
  },
  __v: 0,
  description:
    "Khám phá các phong cách làm tóc phù hợp với từng dịp và cách chọn phụ kiện phù hợp",
};
